"""
Language codes mapping for TranslateGemma.
Based on the comprehensive list of supported languages.
"""

# Mapping from language names (lowercase) to their primary language codes
LANGUAGE_NAME_TO_CODE = {
    'afar': 'aa',
    'abkhazian': 'ab',
    'afrikaans': 'af',
    'akan': 'ak',
    'amharic': 'am',
    'aragonese': 'an',
    'arabic': 'ar',
    'assamese': 'as',
    'azerbaijani': 'az',
    'bashkir': 'ba',
    'belarusian': 'be',
    'bulgarian': 'bg',
    'bambara': 'bm',
    'bengali': 'bn',
    'tibetan': 'bo',
    'breton': 'br',
    'bosnian': 'bs',
    'catalan': 'ca',
    'chechen': 'ce',
    'corsican': 'co',
    'czech': 'cs',
    'chuvash': 'cv',
    'welsh': 'cy',
    'danish': 'da',
    'german': 'de',
    'divehi': 'dv',
    'dzongkha': 'dz',
    'ewe': 'ee',
    'greek': 'el',
    'english': 'en',
    'esperanto': 'eo',
    'spanish': 'es',
    'estonian': 'et',
    'basque': 'eu',
    'persian': 'fa',
    'fulah': 'ff',
    'finnish': 'fi',
    'filipino': 'fil',
    'faroese': 'fo',
    'french': 'fr',
    'western frisian': 'fy',
    'irish': 'ga',
    'scottish gaelic': 'gd',
    'galician': 'gl',
    'guarani': 'gn',
    'gujarati': 'gu',
    'manx': 'gv',
    'hausa': 'ha',
    'hebrew': 'he',
    'hindi': 'hi',
    'croatian': 'hr',
    'haitian': 'ht',
    'hungarian': 'hu',
    'armenian': 'hy',
    'interlingua': 'ia',
    'indonesian': 'id',
    'interlingue': 'ie',
    'igbo': 'ig',
    'sichuan yi': 'ii',
    'inupiaq': 'ik',
    'ido': 'io',
    'icelandic': 'is',
    'italian': 'it',
    'inuktitut': 'iu',
    'japanese': 'ja',
    'javanese': 'jv',
    'georgian': 'ka',
    'kikuyu': 'ki',
    'kazakh': 'kk',
    'kalaallisut': 'kl',
    'central khmer': 'km',
    'kannada': 'kn',
    'korean': 'ko',
    'kashmiri': 'ks',
    'kurdish': 'ku',
    'cornish': 'kw',
    'kyrgyz': 'ky',
    'latin': 'la',
    'luxembourgish': 'lb',
    'ganda': 'lg',
    'lingala': 'ln',
    'lao': 'lo',
    'lithuanian': 'lt',
    'luba-katanga': 'lu',
    'latvian': 'lv',
    'malagasy': 'mg',
    'maori': 'mi',
    'macedonian': 'mk',
    'malayalam': 'ml',
    'mongolian': 'mn',
    'marathi': 'mr',
    'malay': 'ms',
    'maltese': 'mt',
    'burmese': 'my',
    'norwegian bokmål': 'nb',
    'north ndebele': 'nd',
    'nepali': 'ne',
    'dutch': 'nl',
    'norwegian nynorsk': 'nn',
    'norwegian': 'no',
    'south ndebele': 'nr',
    'navajo': 'nv',
    'chichewa': 'ny',
    'occitan': 'oc',
    'oromo': 'om',
    'oriya': 'or',
    'ossetian': 'os',
    'punjabi': 'pa',
    'polish': 'pl',
    'pashto': 'ps',
    'portuguese': 'pt',
    'quechua': 'qu',
    'romansh': 'rm',
    'rundi': 'rn',
    'romanian': 'ro',
    'russian': 'ru',
    'kinyarwanda': 'rw',
    'sanskrit': 'sa',
    'sardinian': 'sc',
    'sindhi': 'sd',
    'northern sami': 'se',
    'sango': 'sg',
    'sinhala': 'si',
    'slovak': 'sk',
    'slovenian': 'sl',
    'shona': 'sn',
    'somali': 'so',
    'albanian': 'sq',
    'serbian': 'sr',
    'swati': 'ss',
    'southern sotho': 'st',
    'sundanese': 'su',
    'swedish': 'sv',
    'swahili': 'sw',
    'tamil': 'ta',
    'telugu': 'te',
    'tajik': 'tg',
    'thai': 'th',
    'tigrinya': 'ti',
    'turkmen': 'tk',
    'tagalog': 'tl',
    'tswana': 'tn',
    'tonga': 'to',
    'turkish': 'tr',
    'tsonga': 'ts',
    'tatar': 'tt',
    'uyghur': 'ug',
    'ukrainian': 'uk',
    'urdu': 'ur',
    'uzbek': 'uz',
    'venda': 've',
    'vietnamese': 'vi',
    'volapük': 'vo',
    'walloon': 'wa',
    'wolof': 'wo',
    'xhosa': 'xh',
    'yiddish': 'yi',
    'yoruba': 'yo',
    'zhuang': 'za',
    'chinese': 'zh',
    'zulu': 'zu',
}

# Mapping from language codes to language names (for display)
CODE_TO_LANGUAGE_NAME = {
    'aa': 'Afar',
    'ab': 'Abkhazian',
    'af': 'Afrikaans',
    'ak': 'Akan',
    'am': 'Amharic',
    'an': 'Aragonese',
    'ar': 'Arabic',
    'as': 'Assamese',
    'az': 'Azerbaijani',
    'ba': 'Bashkir',
    'be': 'Belarusian',
    'bg': 'Bulgarian',
    'bm': 'Bambara',
    'bn': 'Bengali',
    'bo': 'Tibetan',
    'br': 'Breton',
    'bs': 'Bosnian',
    'ca': 'Catalan',
    'ce': 'Chechen',
    'co': 'Corsican',
    'cs': 'Czech',
    'cv': 'Chuvash',
    'cy': 'Welsh',
    'da': 'Danish',
    'de': 'German',
    'dv': 'Divehi',
    'dz': 'Dzongkha',
    'ee': 'Ewe',
    'el': 'Greek',
    'en': 'English',
    'eo': 'Esperanto',
    'es': 'Spanish',
    'et': 'Estonian',
    'eu': 'Basque',
    'fa': 'Persian',
    'ff': 'Fulah',
    'fi': 'Finnish',
    'fil': 'Filipino',
    'fo': 'Faroese',
    'fr': 'French',
    'fy': 'Western Frisian',
    'ga': 'Irish',
    'gd': 'Scottish Gaelic',
    'gl': 'Galician',
    'gn': 'Guarani',
    'gu': 'Gujarati',
    'gv': 'Manx',
    'ha': 'Hausa',
    'he': 'Hebrew',
    'hi': 'Hindi',
    'hr': 'Croatian',
    'ht': 'Haitian',
    'hu': 'Hungarian',
    'hy': 'Armenian',
    'ia': 'Interlingua',
    'id': 'Indonesian',
    'ie': 'Interlingue',
    'ig': 'Igbo',
    'ii': 'Sichuan Yi',
    'ik': 'Inupiaq',
    'io': 'Ido',
    'is': 'Icelandic',
    'it': 'Italian',
    'iu': 'Inuktitut',
    'ja': 'Japanese',
    'jv': 'Javanese',
    'ka': 'Georgian',
    'ki': 'Kikuyu',
    'kk': 'Kazakh',
    'kl': 'Kalaallisut',
    'km': 'Central Khmer',
    'kn': 'Kannada',
    'ko': 'Korean',
    'ks': 'Kashmiri',
    'ku': 'Kurdish',
    'kw': 'Cornish',
    'ky': 'Kyrgyz',
    'la': 'Latin',
    'lb': 'Luxembourgish',
    'lg': 'Ganda',
    'ln': 'Lingala',
    'lo': 'Lao',
    'lt': 'Lithuanian',
    'lu': 'Luba-Katanga',
    'lv': 'Latvian',
    'mg': 'Malagasy',
    'mi': 'Maori',
    'mk': 'Macedonian',
    'ml': 'Malayalam',
    'mn': 'Mongolian',
    'mr': 'Marathi',
    'ms': 'Malay',
    'mt': 'Maltese',
    'my': 'Burmese',
    'nb': 'Norwegian Bokmål',
    'nd': 'North Ndebele',
    'ne': 'Nepali',
    'nl': 'Dutch',
    'nn': 'Norwegian Nynorsk',
    'no': 'Norwegian',
    'nr': 'South Ndebele',
    'nv': 'Navajo',
    'ny': 'Chichewa',
    'oc': 'Occitan',
    'om': 'Oromo',
    'or': 'Oriya',
    'os': 'Ossetian',
    'pa': 'Punjabi',
    'pl': 'Polish',
    'ps': 'Pashto',
    'pt': 'Portuguese',
    'qu': 'Quechua',
    'rm': 'Romansh',
    'rn': 'Rundi',
    'ro': 'Romanian',
    'ru': 'Russian',
    'rw': 'Kinyarwanda',
    'sa': 'Sanskrit',
    'sc': 'Sardinian',
    'sd': 'Sindhi',
    'se': 'Northern Sami',
    'sg': 'Sango',
    'si': 'Sinhala',
    'sk': 'Slovak',
    'sl': 'Slovenian',
    'sn': 'Shona',
    'so': 'Somali',
    'sq': 'Albanian',
    'sr': 'Serbian',
    'ss': 'Swati',
    'st': 'Southern Sotho',
    'su': 'Sundanese',
    'sv': 'Swedish',
    'sw': 'Swahili',
    'ta': 'Tamil',
    'te': 'Telugu',
    'tg': 'Tajik',
    'th': 'Thai',
    'ti': 'Tigrinya',
    'tk': 'Turkmen',
    'tl': 'Tagalog',
    'tn': 'Tswana',
    'to': 'Tonga',
    'tr': 'Turkish',
    'ts': 'Tsonga',
    'tt': 'Tatar',
    'ug': 'Uyghur',
    'uk': 'Ukrainian',
    'ur': 'Urdu',
    'uz': 'Uzbek',
    've': 'Venda',
    'vi': 'Vietnamese',
    'vo': 'Volapük',
    'wa': 'Walloon',
    'wo': 'Wolof',
    'xh': 'Xhosa',
    'yi': 'Yiddish',
    'yo': 'Yoruba',
    'za': 'Zhuang',
    'zh': 'Chinese',
    'zu': 'Zulu',
}

# All supported locale codes (for validation)
SUPPORTED_LOCALE_CODES = {
    'aa', 'aa-DJ', 'aa-ER', 'ab', 'af', 'af-NA', 'ak', 'am', 'an', 'ar', 'ar-AE', 'ar-BH', 'ar-DJ',
    'ar-DZ', 'ar-EG', 'ar-EH', 'ar-ER', 'ar-IL', 'ar-IQ', 'ar-JO', 'ar-KM', 'ar-KW', 'ar-LB',
    'ar-LY', 'ar-MA', 'ar-MR', 'ar-OM', 'ar-PS', 'ar-QA', 'ar-SA', 'ar-SD', 'ar-SO', 'ar-SS',
    'ar-SY', 'ar-TD', 'ar-TN', 'ar-YE', 'as', 'az', 'az-Arab', 'az-Arab-IQ', 'az-Arab-TR',
    'az-Cyrl', 'az-Latn', 'ba', 'be', 'be-tarask', 'bg', 'bg-BG', 'bm', 'bm-Nkoo', 'bn', 'bn-IN',
    'bo', 'bo-IN', 'br', 'bs', 'bs-Cyrl', 'bs-Latn', 'ca', 'ca-AD', 'ca-ES', 'ca-FR', 'ca-IT',
    'ce', 'co', 'cs', 'cs-CZ', 'cv', 'cy', 'da', 'da-DK', 'da-GL', 'de', 'de-AT', 'de-BE',
    'de-CH', 'de-DE', 'de-IT', 'de-LI', 'de-LU', 'dv', 'dz', 'ee', 'ee-TG', 'el', 'el-CY',
    'el-GR', 'el-polyton', 'en', 'en-AE', 'en-AG', 'en-AI', 'en-AS', 'en-AT', 'en-AU', 'en-BB',
    'en-BE', 'en-BI', 'en-BM', 'en-BS', 'en-BW', 'en-BZ', 'en-CA', 'en-CC', 'en-CH', 'en-CK',
    'en-CM', 'en-CX', 'en-CY', 'en-CZ', 'en-DE', 'en-DG', 'en-DK', 'en-DM', 'en-ER', 'en-ES',
    'en-FI', 'en-FJ', 'en-FK', 'en-FM', 'en-FR', 'en-GB', 'en-GD', 'en-GG', 'en-GH', 'en-GI',
    'en-GM', 'en-GS', 'en-GU', 'en-GY', 'en-HK', 'en-HU', 'en-ID', 'en-IE', 'en-IL', 'en-IM',
    'en-IN', 'en-IO', 'en-IT', 'en-JE', 'en-JM', 'en-KE', 'en-KI', 'en-KN', 'en-KY', 'en-LC',
    'en-LR', 'en-LS', 'en-MG', 'en-MH', 'en-MO', 'en-MP', 'en-MS', 'en-MT', 'en-MU', 'en-MV',
    'en-MW', 'en-MY', 'en-NA', 'en-NF', 'en-NG', 'en-NL', 'en-NO', 'en-NR', 'en-NU', 'en-NZ',
    'en-PG', 'en-PH', 'en-PK', 'en-PL', 'en-PN', 'en-PR', 'en-PT', 'en-PW', 'en-RO', 'en-RW',
    'en-SB', 'en-SC', 'en-SD', 'en-SE', 'en-SG', 'en-SH', 'en-SI', 'en-SK', 'en-SL', 'en-SS',
    'en-SX', 'en-SZ', 'en-TC', 'en-TK', 'en-TO', 'en-TT', 'en-TV', 'en-TZ', 'en-UG', 'en-UM',
    'en-VC', 'en-VG', 'en-VI', 'en-VU', 'en-WS', 'en-ZA', 'en-ZM', 'en-ZW', 'eo', 'es', 'es-AR',
    'es-BO', 'es-BR', 'es-BZ', 'es-CL', 'es-CO', 'es-CR', 'es-CU', 'es-DO', 'es-EA', 'es-EC',
    'es-ES', 'es-GQ', 'es-GT', 'es-HN', 'es-IC', 'es-MX', 'es-NI', 'es-PA', 'es-PE', 'es-PH',
    'es-PR', 'es-PY', 'es-SV', 'es-US', 'es-UY', 'es-VE', 'et', 'et-EE', 'eu', 'fa', 'fa-AF',
    'fa-IR', 'ff', 'ff-Adlm', 'ff-Adlm-BF', 'ff-Adlm-CM', 'ff-Adlm-GH', 'ff-Adlm-GM',
    'ff-Adlm-GW', 'ff-Adlm-LR', 'ff-Adlm-MR', 'ff-Adlm-NE', 'ff-Adlm-NG', 'ff-Adlm-SL',
    'ff-Adlm-SN', 'ff-Latn', 'ff-Latn-BF', 'ff-Latn-CM', 'ff-Latn-GH', 'ff-Latn-GM',
    'ff-Latn-GN', 'ff-Latn-GW', 'ff-Latn-LR', 'ff-Latn-MR', 'ff-Latn-NE', 'ff-Latn-NG',
    'ff-Latn-SL', 'fi', 'fi-FI', 'fil-PH', 'fo', 'fo-DK', 'fr', 'fr-BE', 'fr-BF', 'fr-BI',
    'fr-BJ', 'fr-BL', 'fr-CA', 'fr-CD', 'fr-CF', 'fr-CG', 'fr-CH', 'fr-CI', 'fr-CM', 'fr-DJ',
    'fr-DZ', 'fr-FR', 'fr-GA', 'fr-GF', 'fr-GN', 'fr-GP', 'fr-GQ', 'fr-HT', 'fr-KM', 'fr-LU',
    'fr-MA', 'fr-MC', 'fr-MF', 'fr-MG', 'fr-ML', 'fr-MQ', 'fr-MR', 'fr-MU', 'fr-NC', 'fr-NE',
    'fr-PF', 'fr-PM', 'fr-RE', 'fr-RW', 'fr-SC', 'fr-SN', 'fr-SY', 'fr-TD', 'fr-TG', 'fr-TN',
    'fr-VU', 'fr-WF', 'fr-YT', 'fy', 'ga', 'ga-GB', 'gd', 'gl', 'gn', 'gu', 'gu-IN', 'gv',
    'ha', 'ha-Arab', 'ha-Arab-SD', 'ha-GH', 'ha-NE', 'he', 'he-IL', 'hi', 'hi-IN', 'hi-Latn',
    'hr', 'hr-BA', 'hr-HR', 'ht', 'hu', 'hu-HU', 'hy', 'ia', 'id', 'id-ID', 'ie', 'ig', 'ii',
    'ik', 'io', 'is', 'it', 'it-CH', 'it-IT', 'it-SM', 'it-VA', 'iu', 'iu-Latn', 'ja', 'ja-JP',
    'jv', 'ka', 'ki', 'kk', 'kk-Arab', 'kk-Cyrl', 'kk-KZ', 'kl', 'km', 'kn', 'kn-IN', 'ko',
    'ko-CN', 'ko-KP', 'ko-KR', 'ks', 'ks-Arab', 'ks-Deva', 'ku', 'kw', 'ky', 'la', 'lb', 'lg',
    'ln', 'ln-AO', 'ln-CF', 'ln-CG', 'lo', 'lt', 'lt-LT', 'lu', 'lv', 'lv-LV', 'mg', 'mi',
    'mk', 'ml', 'ml-IN', 'mn', 'mn-Mong', 'mn-Mong-MN', 'mr', 'mr-IN', 'ms', 'ms-Arab',
    'ms-Arab-BN', 'ms-BN', 'ms-ID', 'ms-SG', 'mt', 'my', 'nb', 'nb-SJ', 'nd', 'ne', 'ne-IN',
    'nl', 'nl-AW', 'nl-BE', 'nl-BQ', 'nl-CW', 'nl-NL', 'nl-SR', 'nl-SX', 'nn', 'no', 'no-NO',
    'nr', 'nv', 'ny', 'oc', 'oc-ES', 'om', 'om-KE', 'or', 'os', 'os-RU', 'pa', 'pa-IN',
    'pa-Arab', 'pa-Guru', 'pl', 'pl-PL', 'ps', 'ps-PK', 'pt', 'pt-AO', 'pt-BR', 'pt-CH',
    'pt-CV', 'pt-GQ', 'pt-GW', 'pt-LU', 'pt-MO', 'pt-MZ', 'pt-PT', 'pt-ST', 'pt-TL', 'qu',
    'qu-BO', 'qu-EC', 'rm', 'rn', 'ro', 'ro-MD', 'ro-RO', 'ru', 'ru-BY', 'ru-KG', 'ru-KZ',
    'ru-MD', 'ru-RU', 'ru-UA', 'rw', 'sa', 'sc', 'sd', 'sd-Arab', 'sd-Deva', 'se', 'se-FI',
    'se-SE', 'sg', 'si', 'sk', 'sk-SK', 'sl', 'sl-SI', 'sn', 'so', 'so-DJ', 'so-ET', 'so-KE',
    'sq', 'sq-MK', 'sq-XK', 'sr', 'sr-RS', 'sr-Cyrl', 'sr-Cyrl-BA', 'sr-Cyrl-ME', 'sr-Cyrl-XK',
    'sr-Latn', 'sr-Latn-BA', 'sr-Latn-ME', 'sr-Latn-XK', 'ss', 'ss-SZ', 'st', 'st-LS', 'su',
    'su-Latn', 'sv', 'sv-AX', 'sv-FI', 'sv-SE', 'sw', 'sw-CD', 'sw-KE', 'sw-TZ', 'sw-UG', 'ta',
    'ta-IN', 'ta-LK', 'ta-MY', 'ta-SG', 'te', 'te-IN', 'tg', 'th', 'th-TH', 'ti', 'ti-ER',
    'tk', 'tl', 'tn', 'tn-BW', 'to', 'tr', 'tr-CY', 'tr-TR', 'ts', 'tt', 'ug', 'uk', 'uk-UA',
    'ur', 'ur-IN', 'ur-PK', 'uz', 'uz-Arab', 'uz-Cyrl', 'uz-Latn', 've', 'vi', 'vi-VN', 'vo',
    'wa', 'wo', 'zh', 'zh-CH', 'zh-TW', 'zh-Hans', 'zh-Hans-HK', 'zh-Hans-MO', 'zh-Hans-MY',
    'zh-Hans-SG', 'zh-Hant', 'zh-Hant-HK', 'zh-Hant-MO', 'zh-Hant-MY', 'zh-Latn', 'zu', 'zu-ZA',
    'xh', 'yi', 'yo', 'yo-BJ', 'za',
}


def extract_base_code(locale_code: str) -> str:
    """
    Extract the base language code from a locale code.
    
    Examples:
        'en-US' -> 'en'
        'es-ES' -> 'es'
        'zh-Hans' -> 'zh'
        'fr' -> 'fr'
    
    Args:
        locale_code: Locale code (e.g., 'en-US', 'es', 'zh-Hans')
        
    Returns:
        Base language code
    """
    # Split by '-' and take the first part
    return locale_code.split('-')[0]


def is_supported_locale(locale_code: str) -> bool:
    """
    Check if a locale code is supported.
    
    Args:
        locale_code: Locale code to check
        
    Returns:
        True if the locale code is supported
    """
    return locale_code in SUPPORTED_LOCALE_CODES


def get_language_name_from_code(code: str) -> str:
    """
    Get language name from language code.
    
    Args:
        code: Language code (e.g., 'en', 'es', 'fr')
        
    Returns:
        Language name or the code itself if not found
    """
    base_code = extract_base_code(code)
    return CODE_TO_LANGUAGE_NAME.get(base_code, code.capitalize())
